### ISSUE TITLE
bug: invalid enum example in SNIP-12

### ISSUE THREAD

**Issue by thiagodeev** [starknet-io/SNIPs#117]
# Bug Report

**SNIPs version:**
SNIP-12
https://github.com/starknet-io/SNIPs/blob/5d5a42c654c27b377d8b7f90b453065fd19ec2eb/SNIPS/snip-12.md

**Current behavior:**

[here](https://github.com/starknet-io/SNIPs/blob/5d5a42c654c27b377d8b7f90b453065fd19ec2eb/SNIPS/snip-12.md#when-x-is-an-enum), the example says: 
`"type": "(u128, u128*),"`

**Expected behavior:**

without the comma at the end
`"type": "(u128, u128*)"`

**Comment by leo-starkware** [comment]
@thiagodeev could you open a PR about this?

**Comment by gaetbout** [comment]
Did it here: 
https://github.com/starknet-io/SNIPs/pull/118

**Comment by leo-starkware** [comment]
merged
