### ISSUE TITLE
ERC721 Standard Should use felt* instead of felt for tokenURI

### ISSUE THREAD

**Issue by rzmahmood** [starknet-io/SNIPs#14]
Raising this discussion again as it's been discussed a few times but OpenZeppelin has decided to use `felt` instead of `felt*` for `tokenURI`. Their reasoning is discussed [here](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/ERC721.md#interpreting-erc721-uris). This is problematic for the community as it means that no reasonable NFT with metadata can be used as the tokenURI limit of 31 characters is too small for even an IPFS URI

Other entities such as Aspect have also [diverged from the OpenZeppelin Standard](https://github.com/aspectco/cairo-contracts/blob/main/openzeppelin/token/erc721/ERC721_Mintable_Burnable_LongTokenURI.cairo). Having discussed with the team at [LootRealms](https://twitter.com/LootRealms), they will also face this issue.

Immutable X, out of necessity, has also diverged and created an ERC721 standard inspired by OpenZeppelin with a key divergence being the tokenURI. Immutable X provides this as a preset to the community: https://github.com/immutable/imx-starknet/blob/main/immutablex/starknet/token/erc721/presets/ERC721_Full.cairo

Having discussed with [Martín Triay](https://twitter.com/martriay) from OZ, his view was that they would rather wait for StarkNet to release Strings. This unknown date of string support causes issues for organizations wishing to move close to productionizing their apps.

Immutable X will be supporting the long-form Token URI represented using `felt*` as used in [their preset](https://github.com/immutable/imx-starknet/blob/main/immutablex/starknet/token/erc721/presets/ERC721_Full.cairo). Immutable X also presents [encoding and decoding implementation for the tokenURI](https://github.com/immutable/imx-starknet/blob/main/tests/utils/starknetUtils.ts#L60): 

We believe the community should align on enabling organizations to be successful as these organizations will drive users to StarkNet. For NFTs on StarkNet, this means enabling metadata through an extended tokenURI. 

If this gets more than 10 Rocket reacts, I'll make a SIMP for it.

**Comment by fracek** [comment]
If the proposal to return `felt*` from `tokenURI` goes forward I propose to include a strict requirement on how strings should be encoded (should that be another SIMP?) into felts to avoid future issues. For example, a string with 94 characters can be serialized in 4 felts but also in 3 depending on the implementation. Also, should strings be zero terminated or not?

**Comment by rzmahmood** [comment]
> If the proposal to return `felt*` from `tokenURI` goes forward I propose to include a strict requirement on how strings should be encoded (should that be another SIMP?) into felts to avoid future issues. For example, a string with 94 characters can be serialized in 4 felts but also in 3 depending on the implementation. Also, should strings be zero terminated or not?

Agreed that the proposal should be accompanied with a strict standard on the encoding. The nuances can be discussed if this moves ahead. Let me know if there is anything else you would like to see in the encoding standard.

**Comment by fracek** [comment]
Another option is to introduce a new method for StarkNet NFTs (like `metadataURI`) so that tokens are still `ERC721` complaint (by not implementing the optional `ERC721Metadata` interface). I can see this being very confusing for developers so I don't really like it even if it checks all boxes.

**Comment by rzmahmood** [comment]
> Another option is to introduce a new method for StarkNet NFTs (like `metadataURI`) so that tokens are still `ERC721` complaint (by not implementing the optional `ERC721Metadata` interface). I can see this being very confusing for developers so I don't really like it even if it checks all boxes.

The developer experience of this specialized knowledge on ERC721 encoding is not ideal, but the alternative is complete unusability. Furthermore, this. specializing knowledge can be paired with the ERC721 SIMP. 

It's better that it gets used by those who know how than be unusable by everyone.
