### ISSUE TITLE
Prefer felt over uint256

### ISSUE THREAD

**Issue by tarrencev** [starknet-io/SNIPs#15]
Usage of uint256 for backward compatibility with EVM specifications introduces a lot of baggage; increasing storage costs, adding code complexity, and complicating contract interfaces. Given the number of applications that actually need uint256, it seems the costs outweigh the benefits. 

Going forward, most assets in the starknet ecosystem will be starknet native assets, so maintaining backward compatibility with evm types provides only downside. I suggest the base implementation of ERC ports should prefer `felt` over `uint256`. Implementations could chose to maintain a `compat` variant which uses `uint256`.

See previous discussion here: https://github.com/OpenZeppelin/cairo-contracts/issues/336

**Comment by rzmahmood** [comment]
For ERC721s, I would raise a concern that some assets may not be bridgeable from L1 to L2 if their tokenId is outside the felt range. This could be an acceptable tradeoff but one worth noting. Besides that, I would agree.

**Comment by abdelhamidbakhta** [comment]
Shamans related discussion: https://community.starknet.io/t/a-felt-based-erc20-token/1956
